services:
  db:
    container_name: postgres_db
    image: postgres:17-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_DB: 'business_management'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf

  api:
    container_name: fastapi-web
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ./docker/entrypoint.sh

volumes:
  postgres_data: