"""fix: edited User model - added email field, widen first name and last name fields

Revision ID: 16f83fdf81b9
Revises: 79b5d8a2f07b
Create Date: 2025-05-16 16:29:15.045066

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16f83fdf81b9"
down_revision: Union[str, None] = "79b5d8a2f07b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.drop_index("ix_user_email", table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.alter_column(
        "user",
        "email",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
