"""fix: score enum fixed to represent int values

Revision ID: 401851a322a8
Revises: 16f83fdf81b9
Create Date: 2025-05-21 14:23:53.385481

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "401851a322a8"
down_revision: Union[str, None] = "16f83fdf81b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            ALTER TABLE evaluations
            ALTER COLUMN score TYPE INTEGER USING
            CASE score
                WHEN 'ONE' THEN 1
                WHEN 'TWO' THEN 2
                WHEN 'THREE' THEN 3
                WHEN 'FOUR' THEN 4
                WHEN 'FIVE' THEN 5
            END
        """
    )
    # Если нужно, можно удалить тип ENUM после преобразования
    op.execute("DROP TYPE IF EXISTS scoreenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            ALTER TABLE evaluations
            ALTER COLUMN score TYPE scoreenum USING
            CASE score
                WHEN 1 THEN 'ONE'
                WHEN 2 THEN 'TWO'
                WHEN 3 THEN 'THREE'
                WHEN 4 THEN 'FOUR'
                WHEN 5 THEN 'FIVE'
            END
        """
    )
    # ### end Alembic commands ###
