"""feat: added created_at field to evaluations

Revision ID: 8d0b1d3099d2
Revises: 401851a322a8
Create Date: 2025-05-21 14:38:21.231218

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d0b1d3099d2'
down_revision: Union[str, None] = '401851a322a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'created_at')
    # ### end Alembic commands ###
