"""fix: task_id at task_comment now cascade now deleting on cascade

Revision ID: a1d425c07d51
Revises: 3c0a9e728c88
Create Date: 2025-05-24 18:41:33.880461

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1d425c07d51'
down_revision: Union[str, None] = '3c0a9e728c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_comments_task_id_fkey', 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.create_foreign_key('task_comments_task_id_fkey', 'task_comments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
