"""fix: cascade added to evaluations.task_id

Revision ID: e7b74d06e2e3
Revises: a1d425c07d51
Create Date: 2025-05-24 19:16:23.888270

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7b74d06e2e3'
down_revision: Union[str, None] = 'a1d425c07d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('evaluations_task_id_fkey', 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'tasks', ['task_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key('evaluations_task_id_fkey', 'evaluations', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
